<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="3"
            tests="5">

  <testsuite name="test"
    errors="0" failures="3" hostname="" id="" package="test" skipped="1"
    tests="5" time="16.79" timestamp="Wed, 25 Jul 2018 15:32:32 GMT">
  
    <testcase name="default autharisation test" classname="test" time="5.209" assertions="5">

    

    

    

    

    
    </testcase>
  
    <testcase name="wallets" classname="test" time="2.419" assertions="7">

    

      <failure message="Testing if element &lt;.toasted&gt; contains text: &#34;Autharizathion access!&#34;.">    at Object.wallets (/home/evg/WebstormProjects/ale-wallet/test/e2e/specs/tests/test.js:54:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)</failure>

    

    

    

    

    
    </testcase>
  
    <testcase name="here we check wallet logic" classname="test" time="2.780" assertions="10">

    

    

    

    

    

      <failure message="Testing if element &lt;.error&gt; contains text: &#34;send greater than 0&#34;.">    at Object.here we check wallet logic (/home/evg/WebstormProjects/ale-wallet/test/e2e/specs/tests/test.js:92:21)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)</failure>

    

      <failure message="Testing if element &lt;.error&gt; contains text: &#34;You cannot send coins to yourself&#34;.">    at Object.here we check wallet logic (/home/evg/WebstormProjects/ale-wallet/test/e2e/specs/tests/test.js:98:21)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)</failure>

    

    
    </testcase>
  
    <testcase name="here we check sending coins from one my wallet to another my wallet" classname="test" time="6.382" assertions="6">

    

    

    

    

      <failure message="Timed out while waiting for element &lt;button#send-coins&gt; to be present for 5000 milliseconds.">    at Object.here we check sending coins from one my wallet to another my wallet (/home/evg/WebstormProjects/ale-wallet/test/e2e/specs/tests/test.js:120:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)</failure>

    
    </testcase>
  

  

  
    
    <testcase
      name="here we sent from my wallet to wallet on another account" classname="test">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
